Classes/Form/WizardInterface.php

[TASK] Remove obsolete methods getParent() / setParent()

---

Classes/Hooks/ContentIconHookSubscriber.php
ext_localconf.php

[FEATURE] Display icon of Form associated with record

---

Classes/Provider/AbstractProvider.php

- Take ListType and CType additionally into account preventing false hits for custom CTypes

[TASK] Change cache key generation

---

Classes/Provider/AbstractProvider.php

- now considers different CTypes and ListTypes as different clauses

[BUGFIX] Fix full match determining for resolving provider

---

Classes/View/PreviewView.php

- currently only pointer to doc: https://review.typo3.org/#/c/36746/
- fixes step 1 of #763

[TASK] Adapt URL generation for deprecated TYPO3.CMS entry points

---

Classes/Provider/AbstractProvider.php
Classes/Provider/ContentProvider.php

If one had registered for custom CTypes it led to the rendering of wrong
flexform for CTypes 'list' even if that wasn't reg'ed for Flux.

[BUGFIX] Fix trigger method for 'list' CType

---

Classes/Configuration/BackendConfigurationManager.php

Fixes https://github.com/FluidTYPO3/flux/issues/794

[BUGFIX] Set possible wrong currentPageId to null

---

Classes/Backend/TceMain.php
Classes/Provider/LightweightProvider.php

Fixes https://github.com/FluidTYPO3/fluidcontent/issues/233

[BUGFIX] Add special provider resolve handling for moved records

---

Classes/Hooks/ContentIconHookSubscriber.php
Classes/Utility/MiscellaneousUtility.php

[BUGFIX] Fix convention based form icons

---

Classes/Service/FluxService.php
Tests/Unit/Service/FluxServiceTest.php

[BUGFIX] Change from 10 to 0 for root paths

---

Classes/Hooks/ContentIconHookSubscriber.php
Classes/Hooks/LegacyContentIconHookSubscriber.php
Resources/Public/css/icon.css
Tests/Unit/Hooks/ContentIconHookSubscriberTest.php
ext_localconf.php

[BUGFIX] Fix for icons in list view

---

Classes/Backend/LegacyPreview.php
Classes/Backend/Preview.php
Classes/Provider/AbstractProvider.php
Classes/View/LegacyPreviewView.php
Classes/View/PreviewView.php
Resources/Public/js/DragDrop.js
Resources/Public/js/legacyTypo3pageModule.js
ext_localconf.php

This is based on @monosize https://github.com/FluidTYPO3/flux/pull/823
It solves problems with 7 > and 6.2 LTS: https://github.com/FluidTYPO3/fluidpages/issues/246

[BUGFIX] Fix drag and drop issues for current and 6.2 LTS

---

Classes/ViewHelpers/Form/ObjectViewHelper.php
Classes/ViewHelpers/Form/SectionViewHelper.php

[BUGFIX] Added inheritance arguments

---

Classes/Utility/MiscellaneousUtility.php

Related with:
https://github.com/FluidTYPO3/fluidcontent/pull/254

[FEATURE] Adds createIcon function into MiscellaneousUtility

---

ext_tables.php

https://github.com/FluidTYPO3/fluidcontent/issues/231
https://github.com/FluidTYPO3/fluidcontent/issues/255

[BUGFIX] Fix relation problems with Save and New button

---

Classes/Provider/AbstractProvider.php
Tests/Unit/Provider/AbstractProviderTest.php

[BUGFIX] Avoid file_get_contents Exception

---

Classes/Service/ContentService.php

[BUGFIX] Fix tx_flux_parent always equal to 1 when is translated

---

Classes/Utility/MiscellaneousUtility.php

Because we added tmp rendert images the wizard works.

[TASK] Add SVG support for icons

---

Classes/Provider/AbstractProvider.php

PHP Warning: Illegal string offset 'data' in /var/www/clients/client34/web142/web/typo3conf/ext/flux/Classes/Provider/AbstractProvider.php line 555

[BUGFIX] Warning while copying a page

---

Classes/Provider/AbstractProvider.php

This patch addresses #784 and should bring good riddance of the mentioned PHP warning.

[BUGFIX] Ensure array structure

---

Classes/Controller/AbstractFluxController.php

Fixes: https://github.com/FluidTYPO3/fluidcontent_core/issues/197

[BUGFIX] Fix isForeign comparation for FCC and Fluidcontent elements

---

Classes/Utility/MiscellaneousUtility.php
Tests/Unit/Utility/MiscellaneousUtilityTest.php

[BUGFIX] Clean empty fields/element-lists

---

Resources/Public/css/icon.css

Icon position worked only development mode.

[BUGFIX] Icon position in production and LTS

---

Classes/Utility/CompatibilityRegistry.php

[BUGFIX] Static function and remove unused lines

---

Classes/ViewHelpers/Field/Inline/FalViewHelper.php

See https://github.com/FluidTYPO3/fluidpages/issues/285

[DOC] Warn about <flux:field.inline.fal> inside sections

---

Classes/Form/AbstractFormComponent.php
Classes/Utility/RecursiveArrayUtility.php

[FEATURE] Allows paths like Fluidcontent.allowedContentTypes as variable names

---

Classes/Hooks/WizardItemsHookSubscriber.php

For compatible with fluidcontent extends

[TASK] Define type for whitelist

---

Classes/Provider/AbstractProvider.php
Tests/Unit/Provider/AbstractProviderTest.php

I smashed up my repo so here is the new Pull Request for https://github.com/FluidTYPO3/flux/pull/1035

[BUGFIX] Maintain uid and pid of original page

---

Classes/Backend/DynamicFlexForm.php
Classes/Backend/Preview.php
Classes/Form/AbstractFormComponent.php
Tests/Unit/Backend/DynamicFlexFormTest.php
Tests/Unit/Backend/PreviewTest.php
Tests/Unit/Form/AbstractFormTest.php
Tests/Unit/Form/Field/AbstractFieldTest.php
Tests/Unit/Helper/ResolveUtilityTest.php
Tests/Unit/Outlet/Pipe/TypeConverterPipeTest.php
Tests/Unit/View/ExposedTemplateViewTest.php
Tests/Unit/ViewHelpers/Field/ControllerActionsViewHelperTest.php
Tests/bootstrap.php
ext_localconf.php

See individual commits and source code for explanations.

Compatibility patch

---

Classes/Provider/ContentProvider.php

[BUGFIX] Don't move records when copying

---

Classes/View/PreviewView.php

Some methods now return different values and need
conditions to avoid PHP warnings. Other issues exist
beneath this one so it is not the only bugfix needed.

[BUGFIX] Avoid issues with changes in DatabaseConnection

---

Classes/Backend/DynamicFlexForm.php
ext_localconf.php

Adjusts to new hooks coming for FlexForm processing in TYPO3 (see https://review.typo3.org/#/c/48212/)

[TASK] Adjust to new FormEngine flexform hooks

---

Classes/ViewHelpers/AbstractFormViewHelper.php
Classes/ViewHelpers/Content/GetViewHelper.php
Classes/ViewHelpers/Form/DataViewHelper.php
Classes/ViewHelpers/Pipe/AbstractPipeViewHelper.php
composer.json

Required Traits now aliased by LTS as well.

[TASK] Remove fluid-gap dependency

---

Classes/Backend/DynamicFlexForm.php

Corresponding patch for LTS logic.

[BUGFIX] Skip form processing if no Form is resolved

---

Classes/ViewHelpers/Content/GetViewHelper.php
Classes/ViewHelpers/Form/DataViewHelper.php
Classes/ViewHelpers/Form/RenderViewHelper.php

[BUGFIX] Re-Add @inject annotations and FQCN in doc-comments

---

Classes/Controller/AbstractFluxController.php
Classes/Form/AbstractFormField.php
Classes/Outlet/AbstractOutlet.php
Classes/Outlet/OutletArgument.php
Classes/Outlet/Pipe/EmailPipe.php
Classes/Outlet/Pipe/ViewAwarePipeInterface.php
Classes/Outlet/Pipe/ViewAwarePipeTrait.php
Classes/View/ExposedTemplateView.php
Classes/ViewHelpers/Outlet/ArgumentViewHelper.php
Classes/ViewHelpers/Outlet/FormViewHelper.php
Classes/ViewHelpers/Outlet/ValidateViewHelper.php
Classes/ViewHelpers/OutletViewHelper.php
Classes/ViewHelpers/Pipe/EmailViewHelper.php
Tests/Unit/Controller/AbstractFluxControllerTestCase.php
Tests/Unit/Outlet/OutletArgumentTest.php
Tests/Unit/ViewHelpers/AbstractViewHelperTestCase.php
Tests/Unit/ViewHelpers/Outlet/ArgumentViewHelperTest.php
Tests/Unit/ViewHelpers/Outlet/FormViewHelperTest.php
Tests/Unit/ViewHelpers/Outlet/ValidateViewHelperTest.php
Tests/Unit/ViewHelpers/OutletViewHelperTest.php

Testfile for this behavior: https://gist.github.com/mneuhaus/9a8cff9f5b47ad8872eebae2808c54e7

[FEATURE] Outlet Forms

---

Classes/Service/WorkspacesAwareRecordService.php

Before this patch the service would happily return both
placeholders and original records. This patch makes it
correctly unset moved records and perform overlays
when used in an active, non-live workspace.

[BUGFIX] Make workspace aware record service remove placeholders

---

Classes/Backend/TceMain.php

This patches the new hooks setup to process the most
recent version of a record, when moving any record.
This extra update is necessary for the versioned record
to have the correct relationship values, which in turn
makes sure that once published, the published record
will have the correct relationship.

[BUGFIX] Update most recent workspace record version

---

Classes/Backend/TceMain.php

This patch prevents an issue where some input
records either are themselves versioned records
or have no versions (yet). In these cases we move
the properties of the original input record.

[BUGFIX] Only use versioned record if version exists

---

Classes/Backend/TceMain.php
Classes/View/PreviewView.php

Refactors and corrects a few cases where the hook
processing would trigger in unexpected cases.
Fix kindly sponsored by MSI Chicaco - http://www.msichicago.org/

[BUGFIX] Adjust record moving in workspaces

---

.travis.yml
composer.json
ext_emconf.php

PHP 7 branch is only supported/maintained branch.

[REMOVAL] Drop support for PHP 5.x

---

Classes/Form/Field/Select.php
Classes/Provider/AbstractProvider.php
Classes/Provider/ProviderResolver.php
Classes/Service/FluxService.php
Classes/View/PageLayoutView.php
Tests/Unit/Service/FluxServiceTest.php

* Array native functions + closures for filtering / sorting
* Removal of unused code

Various cleanups

---

Classes/Backend/DynamicFlexForm.php

Also simplifies cache retrieval with a class local cache instance.

[BUGFIX] Fix inconsistent returns

---

Classes/View/TemplatePaths.php

Reverse by key to check the path with the highest number first.
Without the wrong templatepath was used (TYPO3 7.6)

[BUGFIX] Without krsort the template order is wrong

---

Classes/Backend/DynamicFlexForm.php

Fixes #1248 if table uid available (record is saved)

[BUGFIX] Resolve DS for FAL image

---

Classes/Backend/FormEngine/ProviderProcessor.php
Classes/Outlet/Exception.php
Classes/View/PageLayoutView.php
Classes/View/PreviewView.php
Tests/Unit/Configuration/FrontendConfigurationManagerTest.php
Tests/Unit/Helper/ContentTypeBuilderTest.php
Tests/Unit/Outlet/Pipe/ViewAwarePipeTraitTest.php
Tests/Unit/View/PageLayoutViewTest.php
Tests/Unit/View/PreviewViewTest.php

This patch:
* Cleans up a few classes (no functional changes, wrapper for mocking)
* Reactivates a disabled test and adapts mocks
* Adds a few basic tests for classes which were not covered

[TASK] Improve unit tests

---

Classes/Utility/MiscellaneousUtility.php

implements fallback for none GNU systems that do not support GLOB_BRACE

ensures GLOB_BRACE is actually available before using it, also

---

Classes/Helper/ContentTypeBuilder.php

- addBoilerplateTableConfiguration : missing frame palette
- addPageTsConfig : missing addToList in  mod.wizards.newContentElement.wizardItems.GROUP.show
- initializeIfRequired : missing closing bracket

[BUGFIX] ContentTypeBuilder TCA and PageTS

---

Classes/Backend/TceMain.php
Classes/Service/ContentService.php

setting the missing flux related data in processCmdmap_beforeStart

[BUGFIX] Copying during drag and drop TYPO3v8.6

---

Configuration/TCA/Overrides/tt_content.php

[BUGFIX] TCA field layout displayed twice in TYPO3v8+

---

ext_emconf.php

This changeset adds psr-4 autoloading information to the extension definition file.

[TASK] Add autoloading information to ext_emconf

---

Classes/Backend/TceMain.php

\FluidTYPO3\Flux\Backend\TceMain::processCmdmap_postProcess was run on all tables and caused an error when moving pages from the clipboard.

[BUGFIX] Missing restriction on table tt_content

---

Configuration/TCA/Overrides/tt_content.php

This fixes #1367 by also registering ContentTypeBuilder::DEFAULT_SHOWITEM for FE.

[BUGFIX] Prevent wrong TCA generation in FE

---

Resources/Public/css/grid.css

Apply hover css to nested content only if mouse is over ce.

[BUGFIX] Grid hover styles in preview

---

Classes/Backend/TceMain.php

I tried to follow the excellent contribution guidelines best as possible (https://fluidtypo3.org/documentation/contributing/contribution-guide.html). composer install was successfull. However vendor/bin/make, vendor/bin/checkstyle and vendor/bin/runtests are missing. 
Ran phpunit manually, 100% pass.
phpcbf had a number of fixes on several files that I did not changed, so I abandoned that.
Hope this is a sufficient PR. If not I will do my best to improve it.

[BUGFIX] Added check for input value (#1407)

---

Classes/ViewHelpers/Wizard/SuggestViewHelper.php

[BUGFIX] Use correct option to search whole phrase or not

---

Classes/Form/Field/File.php
Classes/Form/Field/Inline/Fal.php

According to RenderType description:
https://docs.typo3.org/typo3cms/TCAReference/ColumnsConfig/Type/Group.html#rendertype-default

[BUGFIX] Fixing error issue when editing page properties

---

.travis.yml
Classes/Utility/MiscellaneousUtility.php
Tests/Unit/Hooks/ContentIconHookSubscriberTest.php
Tests/Unit/Utility/MiscellaneousUtilityTest.php
composer.json
ext_emconf.php

Also adjust TER dependency to include TYPO3 9.1
which is supported but needs to be explicitly added
in the TER metadata.

[TASK] Fix composer deps

---

Classes/Form/Field/Text.php
Classes/ViewHelpers/Field/TextViewHelper.php
Tests/Unit/ViewHelpers/Field/TextViewHelperTest.php

flux:field.text gains support for placeholder, similar to flux:field.input.

[FEATURE] Add placeholder attribute to TextViewHelper.

---

Classes/Form/Field/Text.php
Classes/ViewHelpers/FormViewHelper.php

[BUGFIX] PageTSConfig RTE.default.preset ignored

---

Classes/Integration/HookSubscribers/DataHandlerSubscriber.php

Saves fields prefixed with the table name and which exist
in TCA, into the record fields directly. This patch restores
a functionality previously bound to Providers.

[BUGFIX] Restore $table.$field naming transfer to record

---

README.md

Add instructions to install the flux extension via Composer or the TER.

Add instructions for installation

---

Classes/Integration/HookSubscribers/DataHandlerSubscriber.php

$fieldArray[$fieldName] must be an array an 'data' key must be exists

[BUGFIX] $table.$field" named fields

---

Classes/Service/RecordService.php

Use FrontendRestrictionContainer also in TYPO3 8.7
Additional pull request for #1664

[BUGFIX] Respecting Admin Panel preview settings

---

Classes/Integration/FormEngine/UserFunctions.php

With this check it is possible to open page properties without error
again.
Check parameter before processing prevents fatal error.

[BUGFIX] Fix issue #1697: Check parameter before returing boolean

---

Classes/Integration/HookSubscribers/DataHandlerSubscriber.php
Classes/Integration/PreviewView.php

Fixes issues with copying and moving records in a
workspace, and rendering nested content in pages
that were moved in a workspace.
Close: #1724

[BUGFIX] Correctly copy and move records in workspaces

---

Classes/Controller/AbstractFluxController.php

fix #1278450972 TYPO3\CMS\Extbase\Reflection\Exception\UnknownClassException
Class does not exist. Reflection failed.

[BUGFIX] Check if $this->resolveViewObjectName() is not false #1726

---

Classes/Content/TypeDefinition/FluidFileBased/DropInContentTypeDefinition.php
Classes/Core.php
Classes/Service/PageService.php

The list from flux content elements in the `new content element wizard`
is ordered by the template file name.
Resolves: #1759

[TASK] Sort content elements in `new content element wizard` by name

---

class.ext_update.php

in detectFluidPagesNotInstalledAndBackendLayoutFieldsReferenceFluidpages
Fixes: #1793

[BUGFIX] Ensure method returns array to match strict return

---

Classes/Form/Field/Inline/Fal.php

[BUGFIX] Brings back Crop Variants

---

Classes/Service/PageService.php

[BUGFIX] Changes non existing error level 'fatal' to 'error'

---

Classes/Utility/MiscellaneousUtility.php

[BUGFIX] Use string for constant check

---

Classes/ViewHelpers/FieldViewHelper.php

Resolves: https://github.com/FluidTYPO3/flux/issues/1874

[BUGFIX] Default form.field "exclude" attribute to "false"

---

Classes/Integration/HookSubscribers/ContentIcon.php
Resources/Public/css/flux.css

Fix the toggle button in the TYPO3 preview (avoid line return)

[BUGFIX] Fix breaking display of the toggle button in page preview

---

README.md

The link to the ViewHelper Reference in the ReadMe.md has been updated

Update link to ViewHelper Reference

---

Classes/Integration/ContentTypeBuilder.php

[BUGFIX] Fix PHP 8.1 related warning in ContentTypeBuilder

---

Configuration/Services.yaml

Adds (default) dependency injection configuration to Services.yaml (#2000).

[TASK] Add dependency injection configuration.

---

Classes/Integration/HookSubscribers/DataHandlerSubscriber.php

[BUGFIX] Fix undefined array key warning in PHP 8.1

---

Classes/Integration/HookSubscribers/DataHandlerSubscriber.php
Classes/Integration/HookSubscribers/DynamicFlexForm.php

[BUGFIX] Fix several PHP warnings in PHP 8.1

---

Classes/Content/TypeDefinition/RecordBased/RecordBasedContentTypeDefinitionRepository.php
Classes/Integration/HookSubscribers/TableConfigurationPostProcessor.php
Classes/Provider/AbstractProvider.php
Classes/Provider/Interfaces/ControllerProviderInterface.php
Tests/Unit/Content/TypeDefinition/RecordBased/RecordBasedContentTypeDefinitionRepositoryTest.php

[FEATURE] Re-introduce sorting ability

---

Classes/Integration/HookSubscribers/TableConfigurationPostProcessor.php

[BUGFIX] Prevent edge case recursion

---

Classes/Form/AbstractFormField.php
Classes/Form/FieldInterface.php

Removed type of $displayCondition to allow mixed types of array and string
resolves #2080

[BUGFIX] Support array or string for displayCondition

---

Classes/Attribute/DataTransformer.php
Classes/Form/Transformation/DataTransformerInterface.php
Classes/Form/Transformation/DataTransformerRegistry.php
Classes/Form/Transformation/FormDataTransformer.php
Classes/Form/Transformation/Transformer/ArrayTransformer.php
Classes/Form/Transformation/Transformer/BooleanTransformer.php
Classes/Form/Transformation/Transformer/FileTransformer.php
Classes/Form/Transformation/Transformer/FloatTransformer.php
Classes/Form/Transformation/Transformer/FunctionCallTransformer.php
Classes/Form/Transformation/Transformer/IntegerTransformer.php
Classes/Form/Transformation/Transformer/ObjectTransformer.php
Configuration/Services.php
Configuration/Services.yaml
README.md
Tests/Unit/Form/Transformation/FormDataTransformerTest.php
Tests/Unit/Form/Transformation/Transformer/FileTransformerTest.php
Tests/Unit/Form/Transformation/Transformer/ObjectTransformerTest.php

Allows implementers to specify their own form data transformation routines through a proper API.

[FEATURE] Wrap form data transformation in proper API

---

Classes/Service/RecordService.php

There is no check for the existence of the "frontend.preview" aspect, otherwise we will get an AspectNotFoundException and the site will crash.

[BUGFIX] no check for the existence of the aspect frontend.preview

---

Classes/ViewHelpers/Field/InputViewHelper.php

Resolves https://github.com/FluidTYPO3/flux/issues/2181

[BUGFIX] Cast placeholder to string

---

Classes/Content/ContentTypeValidator.php
Classes/Content/TypeDefinition/RecordBased/RecordBasedContentTypeDefinitionRepository.php
Classes/Integration/HookSubscribers/DataHandlerSubscriber.php
Classes/Integration/NormalizedData/Converter/InlineRecordDataConverter.php
Classes/Updates/MigrateColPosWizard.php

Prepares for compatibility with upcoming major Doctrine dependency switch.

[BUGFIX] Switch from PDO to Connection constants

---

Classes/Content/ContentTypeValidator.php
Classes/Content/TypeDefinition/RecordBased/RecordBasedContentTypeDefinitionRepository.php
Classes/Form/Transformation/Transformer/FileTransformer.php
Classes/Integration/FormEngine/UserFunctions.php
Classes/Integration/HookSubscribers/DataHandlerSubscriber.php
Classes/Integration/NormalizedData/Converter/InlineRecordDataConverter.php
Classes/Integration/Overrides/BackendLayoutView.php
Classes/Service/RecordService.php
Classes/Utility/DoctrineQueryProxy.php
Tests/Mock/QueryBuilder.php
Tests/Mock/Result.php
Tests/Unit/Content/TypeDefinition/RecordBased/RecordBasedContentTypeDefinitionRepositoryTest.php
Tests/Unit/Service/RecordServiceTest.php
Tests/Unit/Service/WorkspacesAwareRecordServiceTest.php
phpstan-baseline.neon

Allows Doctrine usage on different major versions which change the way queries are executed and fetched.

[FEATURE] Introduce Doctrine proxy

---

Classes/Controller/AbstractFluxController.php
Classes/Utility/ContentObjectFetcher.php
Tests/Unit/Controller/AbstractFluxControllerTestCase.php
Tests/Unit/Controller/ContentControllerTest.php
phpstan-baseline.neon

Solution is forward-compatible with v13 which does not allow reading content object renderer from ConfigurationManager.

[FEATURE] Introduce ContentObjectFetcher

---

Classes/Form/Transformation/DataTransformerRegistry.php
Configuration/Services.yaml
ext_localconf.php

Fixes problem with usage of transform instructions on 10.4.

[BUGFIX] Add legacy method for registering data transformers

---

Classes/Backend/PageLayoutDataProvider.php
Classes/Integration/FormEngine/ProviderProcessor.php
Classes/Integration/PreviewView.php
Classes/Integration/WizardItemsManipulator.php
Classes/Proxy/SiteFinderProxy.php
Configuration/Services.yaml
Tests/Unit/Backend/PageLayoutDataProviderTest.php
Tests/Unit/Integration/FormEngine/ProviderProcessorTest.php
Tests/Unit/Integration/PreviewViewTest.php
Tests/Unit/Integration/WizardItemsManipulatorTest.php

Necessary because of upcoming core changes to make SiteFinder final.

[FEATURE] Introduce SiteFinder proxy

---

Classes/Form/Transformation/Transformer/FileTransformer.php
Classes/Proxy/ResourceFactoryProxy.php
Tests/Unit/Form/Transformation/Transformer/FileTransformerTest.php

Necessary because of upcoming core changes that make the class final.

[FEATURE] Introduce ResourceFactory proxy

---

Classes/Integration/HookSubscribers/DynamicFlexForm.php
Classes/Integration/NormalizedData/Converter/InlineRecordDataConverter.php
Classes/Proxy/FlexFormToolsProxy.php
Configuration/Services.yaml
Tests/Unit/Integration/HookSubscribers/DynamicFlexFormTest.php
Tests/Unit/Integration/NormalizedData/Converter/InlineRecordDataConverterTest.php

Necessary because of upcoming changes in core which makes this class final.

[FEATURE] Introduce FlexFormTools proxy

---

Classes/Integration/HookSubscribers/ContentIcon.php
Classes/Proxy/IconFactoryProxy.php
Tests/Unit/Integration/HookSubscribers/ContentIconTest.php

Necessary because of upcoming changes in core which makes this class final.

[FEATURE] Introduce IconFactory proxy

---

Classes/Proxy/TemplatePathsProxy.php
Classes/Service/PageService.php
Tests/Unit/Content/ContentTypeFluxTemplateDumperTest.php
Tests/Unit/Form/Container/GridTest.php
Tests/Unit/FormTest.php
Tests/Unit/Service/PageServiceTest.php

Necessary due to a breaking change in Fluid.
Also refactors around TemplateView differences.

[FEATURE] Introduce TemplatePaths proxy

---

Classes/Enum/PreviewOption.php
Classes/Integration/Event/ModifyPageLayoutContentEventListener.php
Classes/Integration/Event/PageContentPreviewRenderingEventListener.php
Classes/Integration/HookSubscribers/Preview.php
Classes/Integration/PreviewRenderer.php
Classes/Integration/PreviewView.php
Classes/Provider/PageProvider.php
Tests/Unit/Integration/Event/ModifyPageLayoutContentEventListenerTest.php
Tests/Unit/Integration/PreviewRendererTest.php

[FEATURE] Apply preview modes to page previews
