Classes/Utility/MiscellaneousUtility.php
Should resolve https://github.com/FluidTYPO3/flux/issues/728
In 6.2 the icon classes duplicated insert. Please test this before merging it. New content also copy icon and reference are using this function.
=> [TASK] Remove obsolete icon classes

Classes/Backend/Preview.php
The tt_content_drawItem function of TYPO3\CMS\Backend\View\PageLayoutView.php already set this variable to TRUE. If it is FALSE, it means another hook modified it because it already rendered the preview of the current item. Therefore, there is no need to set it to TRUE here.
I have an extension with a custom CType that render the preview for its content objects and set drawItem to FALSE, to prevent the default rendering of the preview. However, Flux set it back to TRUE, event if the CType of the content object does not belong to it. Because of this, I saw both the rendered preview of my extension and the default rendered preview from TYPO3, while I'd expect to only see my rendered preview.
=> [BUGFIX] Do not set drawItem variable in Preview

Classes/Provider/AbstractProvider.php, Classes/Provider/ProviderInterface.php, Tests/Unit/Provider/AbstractProviderTest.php, Tests/Unit/Provider/ProviderTest.php
This is sub-task 1 from https://github.com/FluidTYPO3/flux/issues/760. The commit will break `fluidpages` until that extension has assimilated (most of) the code removed in this commit, into the PageProvider.
=> [TASK] Remove all inheritance support from Provider

Classes/Controller/AbstractFluxController.php, Classes/Form/Field/ControllerActions.php, Classes/Provider/AbstractProvider.php, Classes/Provider/ContentProvider.php, Classes/Provider/ProviderInterface.php, Classes/Provider/ProviderResolver.php, Classes/Service/FluxService.php, Classes/View/ExposedTemplateView.php, Classes/ViewHelpers/AbstractFormViewHelper.php, Classes/ViewHelpers/Form/DataViewHelper.php, Classes/ViewHelpers/FormViewHelper.php, Tests/Unit/Controller/AbstractFluxControllerTestCase.php, Tests/Unit/CoreTest.php, Tests/Unit/Form/Field/AbstractFieldTest.php, Tests/Unit/Form/Field/ControllerActionsTest.php, Tests/Unit/Form/Field/TextTest.php, Tests/Unit/Provider/AbstractProviderTest.php, Tests/Unit/Provider/ContentProviderTest.php, Tests/Unit/Provider/ProviderResolverTest.php, Tests/Unit/Service/FluxServiceTest.php, Tests/Unit/View/ExposedTemplateViewTest.php, Tests/Unit/View/PreviewViewTest.php, Tests/Unit/ViewHelpers/Form/DataViewHelperTest.php
This change:
* Refactors Flux's View to use more of the core View's methods, which is now possible due to the recent TemplatePaths addition.
* Refactors Providers to no longer support template sources - only files are supported, which matches the core's View behavior. This prevents unnecessary file loading in cases where templates are already compiled.
* Implements the new TS-fetching wrapper methods on FluxService where applicable.
* Streamlines the use of RenderingContext/ControllerContext when creating Views through FluxService, to match core's behavior.
* Cleans up many classes for transparency and/or legibility, refactors some system operations to methods to allow mocking responses in tests.
* Adjusts CGL - fixes phpdoc inconsistencies, adds a bit of documentation.
=> [TASK] Major spring cleaning (details inside)

Classes/ViewHelpers/Content/GetViewHelper.php
using of `cObjGetSingle('RECORDS', $conf)` instead of `RECORDS($conf)` which is deprecated in TYPO3 8.0.
=> [TASK] Get rid of deprecation log in TYPO3 7.1

Classes/Form/AbstractFormComponent.php
`createField`, `createContainer` and `createWizard` use nearly the same code.
```php
$className = $this->createComponentClassName($type, 'FluidTYPO3\Flux\Form\XXX');
$component = $this->getObjectManager()->get($className);
$component->setName($name);
$component->setLabel($label);
$component->setLocalLanguageFileRelativePath($this->getLocalLanguageFileRelativePath());
$component->setDisableLocalLanguageLabels($this->getDisableLocalLanguageLabels());
return $component;
```
The code has been moved to the new method `createComponent`
=> [TASK] Remove duplicate code

Classes/ViewHelpers/Content/GetViewHelper.php
Since uid is a unique field, it's not required to group by it.
The query fails on other DBMS as MySQL due to the grouping.
=> [BUGFIX] Do not group by uid

Classes/Form/AbstractFormComponent.php, Classes/ViewHelpers/AbstractFormViewHelper.php, Tests/Unit/ViewHelpers/Field/CustomViewHelperTest.php
Follow-up for #809 
Tests run now, but $root->getExtensionName() is now completely gone. Is this a problem?
=> Fix extensionName override support

Classes/Provider/AbstractProvider.php
If a user inserts and saves a "General Plugin" as CE without specifying the list_type the
preview in Backend breaks (happens easily with the quick ce button from gridelements).
This is caused by a falsey matching the correct plugin type if it's empty. As the check for
plugin type is only needed if the row actually contains a plugin we can remove the case
of an empty list_type.
=> [BUGFIX] Fix wrong plugin type matching

Classes/Utility/MiscellaneousUtility.php
This patch fixes an error when saving an empty flexform as described in fluidcontent#256.
=> [BUGFIX] Remove empty data node from flexform XML

Classes/Utility/MiscellaneousUtility.php
This patch makes ``MiscellaneousUtility::cleanFlexFormXml()`` return ``NULL`` in case the resulting XML is all empty thus resetting the according db field to a clean state.
=> [TASK] Clean db field in case flexform is all empty

Classes/Utility/MiscellaneousUtility.php
Closes: #853
As solution we are returning absolute urls instead of relative paths. I thought about another "if" but it is not possible since the issue only occurs in Preview and not in Edit.
=> [BUGFIX] Fix for icons in Preview for 6.2 LTS and master

Classes/Service/ContentService.php
Please note:
If you put gird in gird in gird without direct parent it will pass and still create a endless loop.
We would need always to search to the top. Create a proper page layout.
=> [BUGFIX] Disallow pasting element inside it self (endless loop)

Classes/Service/FluxService.php, Tests/Unit/Service/FluxServiceTest.php
The information being sent is not intended for editor consumption anyway - and the FlashMessage implementation is not safe to use in all contexts (requires a backend user initialised). Replacing it with a plain syslog puts the messages in TYPO3's log instead.
Close: https://github.com/FluidTYPO3/fluidcontent/issues/276
Close: https://github.com/FluidTYPO3/fluidcontent/issues/264
=> [TASK] Replace FlashMessage messaging with syslog

Classes/Provider/ContentProvider.php, Classes/Service/ContentService.php, Classes/View/PreviewView.php, Tests/Unit/Provider/ContentProviderTest.php
This change adapts our paste handling method to understand the changed format coming from TYPO3 since a 6.2.x change.
* Parameters dispatched by drag and drop are no longer predictable the same way
* Vital indicators in parameters are now gone ('top' position no longer sent)
* Parameter count is changed
Our code is now adapted to the new situation in 6.2.14, but the patch very likely breaks any earlier versions.
Close: #905
Close: https://github.com/FluidTYPO3/fluidcontent/issues/270
=> [BUGFIX] Adapt to unannounced API change in TYPO3

Classes/Provider/AbstractProvider.php, Tests/Unit/Provider/AbstractProviderTest.php
Did not return the absolute path in case of a valid descriptor beginning with 'EXT:'
=> [BUGFIX] Template resolution for custom providers

Classes/ViewHelpers/Field/SelectViewHelper.php
Allows you to specify an "no value" element. e.g.  'please select...'
Requires the bugfix from pull request #924
=> [FEATURE] Missing emptyOption argument for flux:field.select

Classes/View/PreviewView.php
TYPO3 seems to have changed the storage of "Show hidden content elements" recently, which causes fluidcontent to not get the flag to
show of hide hidden content elements inside grids, etc.
TYPO3 now defaults to showing hidden content elements if the flag is
not set. To adapt to this this commit adds the same behavior to default
to shoing hidden content elements. as soon as you switch the "Show hidden content elements" to off and on again it works, because then the flag
is present in the session.
=> [BUGFIX] Fix for not showing hidden content elements in grids anymore

Classes/Service/FluxService.php, Tests/Unit/AbstractTestCase.php, Tests/Unit/Backend/PreviewTest.php, Tests/Unit/Backend/TceMainTest.php
This commit fixes a bug in the FluxService which caused problems with different typoscript on seperate pages in the backend. This happened, because the FluxService didn't take the pageId into account for caching the internal typoscript it uses.
fixes #978
=> [BUGFIX] Separating templates on two PID-Rootlines

Classes/View/LegacyPreviewView.php, Classes/View/PreviewView.php, Tests/Unit/View/LegacyPreviewViewTest.php, Tests/Unit/View/PreviewViewTest.php
Reasons are as follows:
* Paste icons require yet another custom format on the two supported versions.
* Paste icons currently broken on both versions.
* Paste icons require custom styling on each version.
* Paste icons have no style equivalent on 7.x
* 7.x in general has no paste icons (uses clickmenu)
* Expecting core solution (possibly not until core's container content feature is done).
Suggest dropping those icons now, as part of Flux 7.3 release.
=> [TASK] Drop custom paste icons

Classes/Provider/AbstractProvider.php, Tests/Unit/Provider/AbstractProviderTest.php
Do not load language overlays of a page if the
currently used language language is the default language.
If the current language is not the default language,
then load the appropriate language overlay only.
Refs #954
=> [BUGFIX] Dont apply localisation to page values in default language

Classes/Form/Field/Select.php
Since TYPO3 7.5 the items in a item list must be of type array.
Uncaught TYPO3 Exception #1439288036
An item in field settings.header.type of table tt_content is not an array as expected
=> [BUGFIX] Wrong converted csv item list.

Classes/Backend/TceMain.php, Classes/Provider/AbstractProvider.php, Classes/Provider/ContentProvider.php, Classes/Provider/ProviderInterface.php, Tests/Unit/Backend/TceMainTest.php
Not only once for each method/id combination.
Partly resolves #961. Moving the first content element into a newly created container works now, but moving elements after this first element does still not work.
=> [BUGFIX] Call provider methods for different commands.

Classes/ViewHelpers/Field/AbstractRelationFieldViewHelper.php
Flux throws an exception Table tt_content field [...]: If both foreign_unique and foreign_selector are set, they must point to the same field.
=> [BUGFIX] Fix default value for 'foreignUnique' field

Classes/Form/AbstractFormField.php
Example with flux form fields:
```html
<flux:field.select name="type" default="0" items="{0:'Variant A',1:'Variant B',2:'Variant C'}" requestUpdate="1"/>
<flux:field.input displayCond="FIELD:type:>:0" name="subheadline"/>
```
The field "type" has a default value of "0".
The field "subheadline" has the displayCond="FIELD:type:>:0".
When creating a new element, then the subheadline is shown -> that is wrong.
=> [BUGFIX] Default of '0' must be '0' and not NULL in TYPO3 > 7.5

Classes/Backend/FormEngine/ProviderProcessor.php, Classes/Provider/AbstractProvider.php, Classes/Provider/ProviderInterface.php, ext_localconf.php
No need to use a complicated core API - a single Provider method can now be used to manipulate everything about the TCA related to the table/type that made the provider trigger.
=> [FEATURE] Allow any Provider to manipulate any TCA detail

Classes/Utility/MiscellaneousUtility.php, Classes/View/PreviewView.php
* Works in TYPO3 7.6.
* Now in the TYPO3 7 design.
=> [FEATURE] Bring back the paste and reference buttons.

Classes/Utility/MiscellaneousUtility.php
During FlexForm cleaning, field nodes are iterated over and specially
flagged fields are removed. This removal happens during iteration and
the change in the array causes the next element to be skipped.
This bug is visible within EXT:fluidpages when saving a page with
no configuration changes. Values that were not specifically set on the
configuration form are saved in the FlexForm XML.
The solution is to gather fieldNodes to be removed, but remove them in a
separate loop.
=> [BUGFIX] Fixed incorrect cleaning of FlexForm XML

Classes/Service/ContentService.php, Classes/View/PageLayoutView.php, Classes/View/PreviewView.php, Tests/Unit/View/PreviewViewTest.php
and respect edit content permissions.
Since TYPO3 7.6 the up and down buttons are hidden.
This commit also includes the correct sorting value geneartion when an element was moved to first position in a grid column.
This pull request replaces #1014
=> [BUGFIX] Disable up and down buttons in in Web->Page

Classes/Controller/AbstractFluxController.php
When using an argument for a flux controller action e.g.
`public function myAction(SomeModel $someModel) {` inside a `PageController`
the arguments were not given to the subRequest what always results in
a `Required argument "someModel" is not set for PageController->my`.
=> [BUGFIX] Arguments in flux controller were not assigned to subrequest

Classes/ViewHelpers/Field/FileViewHelper.php
The code was not rendered correctly: https://fluidtypo3.org/viewhelpers/flux/master/Field/FileViewHelper.html
=> [DOC] Fix flux:field.file example rendering

Classes/ViewHelpers/Field/AbstractRelationFieldViewHelper.php
This corresponds to an earlier change to the foreignUnique property.  Without it, the core throws an UnexpectedValueException within TCAInlineConfiguration->addInlineSelectorAndUniqueConfiguration() about foreign_selector and foreign_unique not being configured properly.
=> [BUGFIX] Initialize TCA foreignSelector as null rather than empty string

Classes/FluxPackage.php, Classes/Form.php, Classes/Package/FluxPackageFactory.php, Classes/Package/FluxPackageInterface.php, Classes/Package/PackageNotFoundException.php, Classes/Service/FluxService.php, Classes/ViewHelpers/AbstractFormViewHelper.php, Classes/ViewHelpers/FormViewHelper.php, Tests/Unit/Helper/ResolveUtilityTest.php, Tests/Unit/ViewHelpers/AbstractFormViewHelperTestCase.php, Tests/Unit/ViewHelpers/Form/ContentViewHelperTest.php, flux.json
Flux Manifest and Package Concept
=================================
To define a JSON-based manifest for Flux, enabling packages (later including non-extensions) to gain control over which features the package provides and how it provides them. And to define an API, PHP-based, that allows the package a dynamic way to affect the features. The manifest and packages being closely linked - the manifest being used to “seed” the Package instance.
The following are the main purposes for using the package/manifest feature:
* To enable configuration-free integration with Flux features based on class name convention lookup (which can be overridden).
* Provide common API on a per-package basis: allowing packages to do things like deliver custom class names Flux will use as substitutes for Flux's …
=> [FEATURE] Package API

Classes/ViewHelpers/Wizard/ListViewHelper.php
Hi,
I get the following error after I try to open the Page Configuration:
``` PHP Runtime Deprecation Notice: Non-static method FluidTYPO3\Flux\ViewHelpers\Wizard\ListViewHelper::getComponent() should not be called statically in /var/www/webroot/typo3conf/ext/flux/Classes/ViewHelpers/AbstractFormViewHelper.php line 46```
I don't know if this is the correct fix, but every other viewhelper ```getComponent``` is static too
=> [BUGFIX] Update ListViewHelper.php

Classes/Form/Field/File.php, Classes/ViewHelpers/Field/FileViewHelper.php
This option enables to set the internalType on the file field in order to change the "storage" of the
field to fal id instead of a path by setting it to "db". By default it's set to "file", which is the same as it
has been so far.
=> [TASK] Add option to set internalType on File

Classes/Service/ContentService.php
The ContentService always "fell back" to the default sys_language_uid
content element to fill out the "tx_flux_parent" column, when you
translate a content element. This produces more problems down the line,
etc. This Change fixes that behavior, by unsetting the translatedParent
variable if no matching translatedParent was found.
=> [BUGFIX] Fix translation Handling

Classes/Service/FluxService.php
If instance type is not the expected type (if implementation registration did not occur or was overridden) we fall back to resolving TypoScript without being aware of the current page UID context.
Close: #1093
=> [BUGFIX] Fallback to page-unaware ConfigurationManager

Classes/Form/Field/Input.php
Whether it was defined or not.
if using <flux:field.input .../> without maximum and minimum, then NULL was used for upper and lower in the range definition.
Since commit https://github.com/TYPO3/TYPO3.CMS/commit/c6d12307dc1de297e373126c181e013216774e6a
this results into an error in the FormEngineValidation.js. NULL is converted to '0'.
A range test of lower 0 to upper 0 will be done and marks the field as not valid if the value is not 0.
There is also a wrong check with the test on $minimum >= 0 or $maximum >= 0. Now it is possible to use negative values for minimum or maximum.
=> [BUGFIX] Range has been inserted for each field in the TCA. 

Classes/Form/Field/Select.php, Classes/ViewHelpers/Field/SelectViewHelper.php
Adds a new argument „showIconTable“ to SelectViewHelper and
corresponding property to FluidTYPO3\Flux\Form\Field\Select to display
a table of option icons beneath the select.
We like to use this to give the user an easy way to select colors from their color scheme.
=> [FEATURE] Add showIconTable option to select component

Classes/Form.php, Classes/Form/AbstractFormComponent.php, Tests/Unit/Backend/TableConfigurationPostProcessorTest.php
Remove 'form' from the label name, otherwise existing labels are no longer recognized.
see comments in https://github.com/FluidTYPO3/flux/commit/41cb134fe6a2ce2bac05fd04152ab5c392ceaba9
=> [BUGFIX] The label names are generated wrong.

Classes/ViewHelpers/Field/RadioViewHelper.php
`SelectViewHelper`'s getComponent() function is static. This one was not :D
=> [BUGFIX] Fix overriding static w/ non-static

Classes/Form/Field/Select.php, Tests/Unit/Form/Field/SelectTest.php
This broke since the generated language path was no longer correct (`$this->name` vs. `$this->getPath()`), as well as the change in `resolveLocalLanguageValueOfLabel` to no longer actually translate the resolved identifiers. Previously, it was checked whether the `$resolvedLabel` was translated or not, and if not, it fell back to using the `$itemName`. Since `resolveLocalLanguageValueOfLabel` now always returns a string starting w/ `LLL:`, this check has been dropped and the label will be empty if no translation is found.
=> [BUGFIX] Fix getTranslateCsvItems for Select field

Classes/Core.php
Allows `\FluidTYPO3\Flux\Core::registerProviderExtensionKey` to be called with a single argument (extension key - Vendor.ExtensionName format) which means the extension gets registered as a provider for *every* possible feature.
Whether or not an extension registered this way then adds resources for a given feature depends solely on the presence of folders/files/templates as defined in FluidTYPO3 conventions.
=> [FEATURE] Register extension key for any controller/feature

Classes/Service/FluxService.php, Tests/Unit/Service/FluxServiceTest.php
Previously, #getAllTypoScript did not cache the configuration when
called from the frontend. This resulted in a rather large performance
overhead, since #removeDotsFromTS was called repeatedly. This commit
modifies the behaviour such that the configuration is always cached.
For comparison, here are some performance measurements from one of the projects I'm working on:
Summary:
Total:    60.6975 secs
Slowest:  0.6516 secs
Fastest:  0.5766 secs
Average:  0.6070 secs
Requests/sec: 1.6475
Status code distribution:
[200] 100 responses
Response time histogram:
0.577 [1] |∎
0.584 [3] |∎∎∎∎
0.592 [11]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
0.599 [17]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
0.607 [17]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
0.614 [26]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
0.622 [11]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
0.629 …
=> [BUGFIX] Always cache TypoScript config in FluxService

Classes/Transformation/FormDataTransformer.php
This is very handy if you like to build up an json configuration object with {v:format.json.encode()}.
Example:
```
<flux:field.checkbox name="slick.autoplay" label="Autoplay" default="0" transform="bool" />
{v:format.json.encode(value:'{settings.slick}')}
```
=> Added boolval() to dataType transformation

Classes/Hooks/WizardItemsHookSubscriber.php, Classes/Provider/AbstractProvider.php, Classes/View/PreviewView.php, Classes/ViewHelpers/Field/TextViewHelper.php
Execute the PostProcessing of records also when they are newly created. This is to ensure that the property 'id' of section objects is available right after creating a new content element.
Close: #1165
=> [BUGFIX] PostProcess records on creation

Classes/Provider/AbstractProvider.php, Tests/Unit/Provider/AbstractProviderTest.php
This PR ports the fixes of issue #954 into the legacy branch (Do not load language overlays of a page if the currently used language language is the default language).
=> Fix localisation of page values in legacy branch

Classes/Service/ContentService.php, Tests/Unit/Service/ContentServiceTest.php
Backport of PR #1188 into the legacy branch, which is a bugfix for issue #1176
=> Dont assign random flux parent to translations in legacy branch

ext_localconf.php
This allows various cached Flux data sets to remain
cached for 30 days without needing special care
from the site administrator.
=> [TASK] Increase default cache lifetime to 30 days

Classes/Service/FluxService.php, Classes/View/ViewContext.php
This implements memoizers to avoid doing expensive processing
when the output of a method depends is static when the same
input is provided.
Saves SQL requests and TS parsing aplenty.
=> [BUGFIX] Implement memoizer for frequently called FluxService methods

Classes/View/ExposedTemplateView.php
This patch restores template compiling behavior when templates are
rendered through the ExposedTemplateView on TYPO3v8 and above.
Before this patch the source would be parsed every time.
=> [BUGFIX] Restore template compiling in ExposedTemplateView on v8+

Classes/ViewHelpers/AbstractFormViewHelper.php, Classes/ViewHelpers/Content/GetViewHelper.php, Classes/ViewHelpers/Form/DataViewHelper.php, Classes/ViewHelpers/Pipe/AbstractPipeViewHelper.php, composer.json
Note: contains a second commit from another PR which is needed to even trigger compiling on TYPO3v8+. Will be rebased once https://github.com/FluidTYPO3/flux/pull/1204 is merged.
=> [FEATURE] Compile ViewHelpers using namelesscoder/typo3-cms-fluid-gap

Classes/Backend/DynamicFlexForm.php, Classes/Form.php, Classes/ViewHelpers/Form/Option/StaticViewHelper.php, Tests/Unit/Backend/DynamicFlexFormTest.php, Tests/Unit/ViewHelpers/Form/Option/StaticViewHelperTest.php
Setting `<flux:form.option name="static" value="1" />` causes
the DS to be cached statically. Useful when the form extracted
from the template is always the same (e.g. not dynamic).
=> [FEATURE] Form option to cause static caching

Classes/Utility/ExtensionNamingUtility.php
This implements a memoizer in ExtensionNamingUtility
in the methods which use PHP functions; leaves the
ones that use language structs alone. On a test setup
with just six instances of a content element from a
provider extension this saves ~500 calls to trimexplode.
Impacts memory usage slightly (+1.3% on test setup).
=> [TASK] Implement memoizer to avoid repeated calls

Classes/View/ExposedTemplateView.php
Flux throws an exception if no grid is defined, this change catches that exception and returns null.
closes: #1212
=> [BUGFIX] Catch exception if no grid is defined

Classes/ViewHelpers/Content/GetViewHelper.php, Classes/ViewHelpers/Content/RenderViewHelper.php, Classes/ViewHelpers/Form/RenderViewHelper.php
Needs https://github.com/FluidTYPO3/flux/pull/1217 first, then a rebase. Other fix included to make the PR testable as-is. Fixes escaped output of nested content rendering.
=> Fixescapeoutput

Classes/Hooks/ContentIconHookSubscriber.php
Since TYPO3 only writes non NULL values to `tt_content.pi_flexform` when having at least one `<flux:field.*>` in the `fluidcontent` template configuration most of the fluidcontent element icons are missing in page and list module.
=> [BUGFIX] Icons of fluidcontent elements missing

.travis.yml
Nobody uses it since the advent of PHP 7
=> [TASK] Remove hhvm from build config

Classes/Hooks/WizardItemsHookSubscriber.php, Tests/Unit/Hooks/WizardItemsHookSubscriberTest.php
PHP 7.1 doesn't allow creating array lazily / on-demand.
Fixes one of the PHP 7.1 builds
Contains a second commit that transforms the soup that was the WizardItemsHookSubscriberTest
into a more readable dish.
=> [BUGFIX] Create array explicitly when applying defaults

.travis.yml
This commit doesn't allow failures with 7.1 anymore.
RC6 is the last release candidate and the test-suite is fine
beginning with #1231.
=> [TASK] Make tests with PHP 7.1 mandatory

Classes/ViewHelpers/Form/DataViewHelper.php
In fully compiled templates the injection methods will not
execute since a VH class instance is never created. The
classes used are now wrapped in a getter method to create
instances as needed.
NB: inject annotation removed, injection method preserved
in order to allow replacing instances from the outside in a
way that still works with uncompiled rendering.
Close: #1228
=> [BUGFIX] Fix DataViewHelper when injectors don't execute

Classes/Controller/AbstractFluxController.php
Avoids an exception if for whatever reason, the
initializeView method on a Flux controller gets
called twice. Overriding the variables is safe.
Close: #1243
=> [BUGFIX] Avoid "variable already set" Exception

Classes/Form/AbstractMultiValueFormField.php
If In TYPO3 8.5 using an inline field with ```<flux:field.inline.fal>``` or ```<flux:field.inline>``` the output is a select box and not an inline container.
Setting the default value to an empty string is secure, cause the renderType argument of the select ViewHelper use "selectSingle" as default argument.
=> [BUGFIX] Setting default value of RenderType to an empty String

Classes/View/PreviewView.php, Tests/Unit/View/PreviewViewTest.php
Fixes an issue where child content would be shown as
duplicated (same tt_content UID in multiple places).
The following symptoms are fixed:
* New child content shows as duplicated
* Edited child content shows as duplicated
* Published changes not shown in workspace
* "Show hidden" option not respected correctly
The fixes are achieved by:
* Adding the current PID restriction to SQL query
* Adding workspaces fields restrictions to SQL query
* Correcting the referencing of $moduleData from
undefined class property to correct local variable.
=> [BUGFIX] Fix child content display in BE workspace

Classes/ViewHelpers/Content/GetViewHelper.php
This patch solves issues with flux:content.get and
flux:content.render, which made those return an
incorrect set of nested content elements when
previewing in the frontend.
=> [BUGFIX] Output correct nested content in workspaces

Classes/Service/ContentService.php, Tests/Unit/Service/ContentServiceTest.php
This patch solves a problem where updating a record
while editing a workspace also caused some of those
edits to be performed on the live content record as
well. By switching from directly updating the database
over to updating the DataHandler data map array, the
issue is avoided.
=> [BUGFIX] Do not perform direct DB writes in moveRecord

Classes/Configuration/ConfigurationManager.php, Classes/Configuration/FrontendConfigurationManager.php, Tests/Unit/Configuration/ConfigurationManagerTest.php
Adds a workaround for https://forge.typo3.org/issues/79098
which will for some time be required to avoid a fatal
php error when using the new API to register template files
as new content types.
=> [BUGFIX] Work around pre-TS ConfigurationManager use

Classes/Backend/TceMain.php, Classes/Service/ContentService.php, Classes/Utility/MiscellaneousUtility.php, Classes/View/PreviewView.php, Classes/ViewHelpers/Content/GetViewHelper.php, Tests/Unit/Utility/MiscellaneousUtilityTest.php, ext_tables.php
Adds a few further bug fixes:
* Switched to post-processing move hooks since these
are the only ones to receive the necessary input values.
* Implemented necessary saving of record after post hooks,
since record has already been saved by core.
* Turned colPos into a positive value to make the core read
it as such.
* Corrected PreviewView to insert the target colPos value.
* Added version copy shadow columns configuration to make
newly created versions inherit column positions.
* Fixed FE preview output to exclude versioned placeholders.
This should be the last required fix for drag and drop support
in the backend. Moving of both original records and placeholders
is now fully supported; however, bugs still remain in the publish
process (which reverts the colPos to an incorrect value).
Fix …
=> [BUGFIX] Fix moving relative to other element

Classes/Backend/TceMain.php, Classes/View/PageLayoutView.php, Classes/View/PreviewView.php, Tests/Unit/View/PreviewViewTest.php
Restores support for pasting content elements as copies
both in temporary and live workspaces. Specifically:
* Reacts to "copy" command
* Resolves the copy that was created, performs operations on it
* Updates the move placeholder / most recent version if one exists
* Fixes display of move placeholders in nested content area
when the move placeholder is hidden (which copies are by
default, unless this is changed per site). Does so by reproducing
the logic of PageLayoutView::getResult without unsetting placeholders.
=> [BUGFIX] Restore broken "paste as copy" operation

Classes/Backend/TceMain.php, Classes/View/PreviewView.php
This fixes an issue where TYPO3 receives an incorrect
target page UID when a drag-and-drop action is performed.
=> [BUGFIX] Correct parameters for record moving on LTS in workspace

Classes/Backend/TableConfigurationPostProcessor.php, Classes/Core.php, Classes/Helper/ContentTypeBuilder.php, Tests/Unit/CoreTest.php
Class loading via ObjectManager had to be delayed
since the database connection is not initialized yet
on LTS when reading ext_localconf.php files.
Logic which creates class has been moved to the
table configuration post processing hook where the
CType is also registered.
=> [BUGFIX] Adapt custom CType registration to work on LTS

Classes/View/PreviewView.php
PreviewView contained remnants of manual workspace
overlaying - this logic needs to be removed since it is
now taken care of by getRecords() itself.
=> [BUGFIX] Remove now redundant workspaces processing

Classes/Utility/MiscellaneousUtility.php, Tests/Unit/Utility/MiscellaneousUtilityTest.php
This PR changes the way Flux cleans a FlexForm. One of the things done by this cleaning function was to delete all the empty `sheet` elements, because it makes TYPO3 throw an exception in some cases.
But there was a problem in the way this feature was handled: looping on the elements and removing elements at the same time could cause nodes to be skipped. For instance, if three `sheet` nodes were empty in a row, the second one was skipped because the first one was removed and the looping pointer was not correctly updated.
The implemented solution to this (big) issue is to first loop on all `sheet` nodes, and store the one which _should_ be deleted first, _then_ loop again on this list and remove the nodes one by one.
One unit test has also been added to check that the solution works the …
=> [BUGFIX] Fix FlexForm empty nodes removal

Classes/Service/FluxService.php
This fixes the error "The property "options.Fluidcontent.sorting" on the subject was not accessible" caused by Fluidcontent. Tested on Typo3 7.6.15 with Flux 8.0.0 and Fluidcontent 4.4.1.
=> [BUGFIX] Fixes accessing the "options.Fluidcontent.sorting"

Classes/Backend/DynamicFlexForm.php
The cache key generation was bogus and thus never effective.
There's still a bunch of incorrect returns which I'll remove in a followup.
=> [BUGFIX] Write caches correctly in DynamicFlexForm

ext_localconf.php
The extTablesInclusion-PostProcessing hook behaves
unpredictably in FE when no BE user is logged in and
caches expire. In order to trigger the hook consistently,
the same hook subscriber must be registered in two
places, depending on BE or not BE context.
Specifically, prevents missing TCA in the case described
above - and allows template-as-CType registrations to
function correctly.
=> [BUGFIX] Split TCA post processing hook into two

Classes/View/PreviewView.php, Resources/Public/css/grid.css
Using the same design from the page column labels.
#1280
=> [BUGFIX] Show label of flux:grid.column again

Classes/Service/FluxService.php, README.md, Tests/Unit/Service/FluxServiceTest.php, class.ext_update.php, ext_emconf.php
Hey guys,
this PR will backport 
* EM Update script for flux parent patch (#1176)
* Cache TypoScript config to improve performance (#1140)
to the legacy branch.
I have also added a note about the legacy branch to the Readme.
=> Backport EM Update script and TS Cache to legacy branch

Classes/Hooks/ContentIconHookSubscriber.php, Classes/View/PreviewView.php, Resources/Private/Language/locallang.xlf, Resources/Public/css/grid.css, Resources/Public/css/icon.css, Resources/Public/js/fluxCollapse.js, Tests/Unit/Hooks/ContentIconHookSubscriberTest.php, Tests/Unit/View/PreviewViewTest.php
Displaying the toggler in the header of the element.
Right next to the edit / hide / delete / buttons.
Bugfix in fluxCollapse.js
Array.isArray() is used to check whether the cookie variable is of type "array" and to avoid javascript errors.
Optimizing Cookie handling; remove "null" items from cookie array.
Tested in TYPO3 7.6.15
=> [BUGFIX] Fix design for collapsing columns

Classes/View/PreviewView.php
Hidden elements in grid columns wasn't hide if the 'show hidden content element' checkbox wasn't checked.
=> [BUGFIX] Show hidden content elements

Classes/Service/ContentService.php
The uid of the element to be moved must be specified here.
=> [FOLLOWUP][BUGFIX] Use correct relative-to argument for sorting

Classes/Configuration/BackendConfigurationManager.php, Tests/Unit/Configuration/BackendConfigurationManagerTest.php
This commit fixes a severe issue that would return a completely wrong page id for a given record upon creation.
This could lead to really severe issue. For instance the wrong TypoScript tree was loaded for a new content using FluidContent, only on creation.
I did only add `tt_content` to the list, but I really think we should consider modify this condition to be only checking the command type to be `new`, as every record just can't have a pid when it is not even created in database yet.
=> [BUGFIX] Add `tt_content` in list of tables affected by `new` command

Classes/Backend/DynamicFlexForm.php, Classes/Hooks/ContentIconHookSubscriber.php, ext_localconf.php
Flux minimal TYPO3 version is 7.6.13 and all entries with CompatibilityRegistry are for 7.6.0.
So we don't need them anymore.
remove CompatibilityRegistry::get in \FluidTYPO3\Flux\Backend\DynamicFlexForm and in \FluidTYPO3\Flux\Hooks\ContentIconHookSubscriber
=> [TASK] Remove CompatibilityRegistry in ext_localconf.php

Classes/Helper/ContentTypeBuilder.php, Configuration/TCA/Overrides/tt_content.php
move showItem configuration into ext_localconf.php - using CompatibilityRegistry
convert arrays in ext_localconf.php into short arrays
=> [BUGFIX] ContentTypeBuilder LTS

Classes/Backend/TceMain.php, Classes/Form/AbstractFormField.php, Classes/Service/ContentService.php, Classes/Utility/ClipBoardUtility.php, Classes/View/PreviewView.php, Tests/Unit/Backend/TceMainTest.php, ext_localconf.php
since v8.6 the paste icons are inserted with javascript.
change the icon from "actions-document-paste-after" into "actions-document-paste-into" for TYPO3 version lower than 8.6
=> [BUGFIX] Paste into icon is shown twice in TYPO3v8.6

Classes/ViewHelpers/Form/DataViewHelper.php
In addition to https://github.com/FluidTYPO3/flux/pull/1215 above changes are required.
I use customize fluidstyledcontent templates in my project and without that fix I can not access piflexform data from within them.
=> [BUGFIX] Adapt to FlexForm language handling deprecation

Classes/Backend/DynamicFlexForm.php
The method had one case where the TCE wrapper patch method would not be called
on the data that was fetched from cache.
This commit fixes this case, which seems to be the only one that was forgotten.
=> [BUGFIX] Apply TCE wrapper patch on data structure fetched from cache

Classes/Service/RecordService.php
Part of https://github.com/FluidTYPO3/fluidcontent/issues/415
Without that patch, accessing the web module in the TYPO3 backend will result in an SQL error:
```
An exception occurred while executing '
SELECT `pid` FROM `sys_template`
WHERE (root = 1
AND deleted = 0
AND hidden = 0
AND starttime <= :starttime
AND (endtime = 0 OR endtime > :endtime)
)
AND (
(`sys_template`.`deleted` = 0)
AND (`sys_template`.`hidden` = 0)
AND (`sys_template`.`starttime` <= 1500891480)
AND ((`sys_template`.`endtime` = 0) OR (`sys_template`.`endtime` > 1500891480))
)
':
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '
:starttime AND (endtime = 0 OR endtime > :endtime)) AND ((`sys_template`.`delete
' at line 1
```
=> [BUGFIX] Pass values to query builder

Classes/Form/Field/Inline.php, Classes/Form/Field/Relation.php
After https://github.com/FluidTYPO3/flux/commit/0bd5466f85b0ad9962803a396d7a9ac624c65cc4
field.inline and field.relation are not working as expected
=> [BUGFIX] Brings back Inline and Relation fields expected behaviour

Classes/ViewHelpers/Content/GetViewHelper.php
If a fluidcontent element containing other content elements is added as "insertRecord" into a page, then currently the child records are not found anymore, because the pid is wrong. TYPO3 used by default the pid of the currently rendered page, but if you used "insertRecord" for your container element, then the pid for the childs records will be different, they always match the pid of the container element.
=> [BUGFIX] find child records also with "insertRecord"

Classes/Form/Field/Input.php
Checking for 'int' in the validator list is needlessly
limiting. range works just as well e.g. with double2 fields.
=> [BUGFIX] Set input field range independent of validators

Classes/Service/FluxService.php, Tests/Unit/Service/FluxServiceTest.php
Problem should be obvious, basically `getTypoScriptByPath` will not work at all at the moment.
=> [BUGFIX] Fix FluxService->getTypoScriptByPath not working 

Classes/Service/ContentService.php
It seems that \FluidTYPO3\Flux\Service\ContentService::moveRecord is surprisingly called with target pid in parameter $relativeTo if editor is cutting and inserting a content record via clipboard. Only on big pagetrees this leads to lost content elements, because colPos is set to 18181 then even for regular content elements.
Since the flux colPos only makes sense, if we have a tx_flux_parent, this pull request fixes that issue.
I am fully aware that this fix is likely not targeting the root cause of the problem (getting the pid for the parameter $relativeTo) but i was not able to fully grasp what should be going on here.
Thus i hope this helps at least as hotfix for people affected by this problem.
=> [BUGFIX] Set flux colPos for moved records only if correct

ext_tables.sql
If you have a few more sites, the originally used SMALLINT column does not fit the longer colPos values
=> [BUGFIX] Increase integer size of colPos SQL column

Classes/Form/Field/Tree.php
Form/Field/Tree has not set the renderType and there are no getters or setters to add it.
The renderType is mandatory.
=> [TASK] Add renderType to Form\Field\Tree.

Classes/Service/RecordService.php
This fixes the case where `reset([])` returned `FALSE`, but should return `NULL` to match the method signature doc comments.
> [**reset()**](http://php.net/manual/en/function.reset.php) rewinds array's internal pointer to the first element and returns the value of the first array element. – Returns the value of the first array element, or **FALSE** if the array is empty.
As a side effect this fixes an endless loop in fluidpages described in https://github.com/FluidTYPO3/fluidpages/issues/390, because the [`FluidTYPO3\Fluidpages\Service\PageService->getPageTemplateConfiguration()`](https://github.com/FluidTYPO3/fluidpages/blob/development/Classes/Service/PageService.php#L145) depends on the documented return type of `RecordService->getSingle()` to abort the loop.
=> [BUGFIX] Fix RecordService->getSingle return type

Classes/Form/Field/Inline/Fal.php, Classes/ViewHelpers/Field/Inline/FalViewHelper.php
Fixes #1433 
Pretty straightforward, I added a `cropVariant` attribute to `flux:field.inline.fal`.
The example I added creates this crop wizzard:
=> [FEATURE] Allow cropVariants definition for FAL fields

Classes/ViewHelpers/Field/Inline/FalViewHelper.php
There was an example on how to use the new cropVariants property to define the flux form already, added an example on how to use the crop data in the frontend.
Added this because I got a request on how to actually use the feature in the original PR: https://github.com/FluidTYPO3/flux/pull/1660#issuecomment-458134267
=> [DOC] Add example on how to use cropVariants

Classes/Form/AbstractFormField.php, Classes/Form/FieldInterface.php, Classes/ViewHelpers/Field/AbstractFieldViewHelper.php
Allows users to pass "config" to Flux form fields and
provide any TCA option, including those that are not
supported as ViewHelper attributes. Values specified
in this array will have priority over other properties.
=> [FEATURE] Allow arbitrary TCA "config" array on fields

class.ext_update.php
Migrating a large data set of content elements can/will cause memory exhausted
exceptions. Using `unset` on `$row` and `$grid` variables deals with this. Migration of an installation with over 25000 entries runs fine after this changes.
=> [BUGFIX] Handle memory leaks on large mirgation data sets

Classes/Integration/HookSubscribers/DataHandlerSubscriber.php
When trying to copy child records, do not copy deleted ones.
Steps to reproduce:
1. Create an element that allows children (grid)
2. Create a child element
3. Delete child element
4. Copy and paste the main element
5. Error occurs, since deleted child element is tried to be copied.
Close: #1704
=> [BUGFIX] Do not try to copy deleted records

Classes/Integration/PreviewView.php
Used TYPO3 Version: 8.7.27
Used Flux Version: dev-development
Having a parent record with sys_language_uid -1 and a child
record with sys_language_uid 0 will result in the child record
not being shown. This happens because till now the respected
sys_language_uid of the child record will be set to the parent
record, which would be -1. This results in a query looking for
the record with sys_language_uid = -1, which dosn't exist.
The normal behaviour should respect the currently selected
language in the Backend as in the Backend/PageLayoutController
shown in Line 926 (TYPO3 8).
=> [BUGFIX] Fixed language handling for nesting

Configuration/TCA/Overrides/pages.php, Configuration/TCA/Overrides/pages_language_overlay.php, Configuration/TCA/Overrides/sys_template.php
As of TYPO3 CMS v9 the extension configuration stored in $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf'] has been replaced by a plain array in $GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS'].
Resolves: #1781
=> [BUGFIX] Respect new extension configuration API

Classes/Integration/HookSubscribers/DataHandlerSubscriber.php
When creating a new Record processDatamap_afterDatabaseOperations is
called with $fieldArray['t3_origuid'] = 0. However the handler should
exit early when this is not a newly created translation.
Fixes #1786
=> [BUGFIX] Make sure the creation of content elements works

class.ext_update.php
The trailing comma in function arguments syntax was added in PHP 7.3.
As this extension should be backwards compatible with TYPO3 9.5 it needs
to run on PHP 7.2.
Fixes #1784
=> [BUGFIX] ensure compatibility with PHP 7.2

Classes/Core.php, Classes/Provider/AbstractProvider.php
The current checks for absolute file paths currently disregards Windows file paths.
This patch introduces PathUtility::isAbsolutePath to respect both, Unix and Windows paths.
Resolves: #1752
=> [BUGFIX] Respect absolute file paths on Windows systems

Classes/Form/AbstractInlineFormField.php, Classes/Form/Field/Inline/Fal.php, Classes/ViewHelpers/Field/Inline/FalViewHelper.php
This migrates the inline fal configuration from using the now removed
foreign_selector_fieldTcaOverride to overrideChildTca.
Fixes #1774
=> [BUGFIX] Make sure inline fal works with TYPO3 10

Classes/Service/PageService.php
Avoids multiple calls to getAvailablePageTemplateFiles
causing performance detriment.
=> [BUGFIX] Store resolved page forms in runtime cache

Classes/Integration/ContentTypeBuilder.php, Classes/Outlet/Pipe/AbstractPipe.php, Classes/Outlet/Pipe/ControllerPipe.php, Classes/Outlet/Pipe/EmailPipe.php, Classes/Outlet/Pipe/FlashMessagePipe.php, Classes/Outlet/Pipe/PipeInterface.php, Classes/Outlet/Pipe/TypeConverterPipe.php, Classes/ViewHelpers/Outlet/FormViewHelper.php, Classes/ViewHelpers/Pipe/AbstractPipeViewHelper.php, Classes/ViewHelpers/Pipe/TypeConverterViewHelper.php, Resources/Private/Language/locallang.xlf, Tests/Unit/Outlet/Pipe/AbstractPipeTestCase.php, Tests/Unit/Outlet/Pipe/EmailPipeTest.php, Tests/Unit/Outlet/Pipe/StandardPipeTest.php
Revives the Outlet feature by cleaning up the implementation
and removing the form fields integration so that Outlet/Pipe
is now exclusively configured at Form level. Adds TYPO3 10.4
support to the EmailPipe, and adds a "property" argument for
the TypeConverterPipe to allow converting only a single
property in the posted form data array.
Close: #1379
Close: #1095
=> [FEATURE] Revive Outlet feature

Classes/Integration/ContentTypeBuilder.php, ext_localconf.php
Use full class name instead of short handle on TYPO3
versions that support using FQCN.
=> [BUGFIX] Use controller FQCN on TYPO3 10.4+

Classes/Content/ContentTypeManager.php
I've discovered the problem with Issue #1866 where the content types selection only worked when the Plug & Play checkbox was selected.
During my xdebug fiddling I noticed that even I had 2 flux based extensions and the Plug & Play enabled the CEs of first extension didn't get listed in the 'Available content types' list.
After a bit more of debugging I came down to this line where the `$this->typeNames` were replaced instead of added to the already existing one.
After I've changed the line it worked even without Plug & Play selection.
=> [BUGFIX] Fix content type Available content types

Classes/Integration/HookSubscribers/DataHandlerSubscriber.php
When copying on list view, `$value` comes as a negative integer indicating the id of the content after which is going to be pasted. A simple `is_array` conditions seems to work.
Resolves: #1816
=> [BUGFIX] Avoid error when copying on list

Classes/Integration/PreviewView.php
Copy 5fde1b6d2cd448e6ad64c7a3f70a7de4ad79190f which once fixed #1620 to solve #1850
=> [BUGFIX] Show column label instead of colPos (page translation view) 

Classes/Integration/HookSubscribers/DataHandlerSubscriber.php
Fixes resolving of copied parent record by avoiding
selection of the workspace placeholder record, and
fixes undesired resetting of colPos after DataHandler
by also setting the new colPos value in placeholders.
Close: #1895
=> [BUGFIX] Fix copy/paste of parent in workspace

Classes/Controller/AbstractFluxController.php
The custom controller actions breaks in Typo3 11, because the process function for the custom functions got changed. I already got a working solution for the problem, but i want to describe it first.
In flux, the action is called here: https://github.com/FluidTYPO3/flux/blob/development/Classes/Controller/AbstractFluxController.php#L447
But with typo3 11, the parameters got changed. The response is no parameter anymore, it's the result. Extbase code: https://github.com/TYPO3/typo3/blob/main/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php
I fixed the problem with a version check for the Typo3 version. So it is also working for older versions of Typo3.
=> [BUGFIX] Custom controller actions in Typo3 11 with new return types

Classes/Updates/MigrateColPosWizard.php, ext_localconf.php
Copying pages will fail to adjust the colPos values when the "sorting" value
of child elements is larger than that of its parent record.
This leads to "lost" content records that are visible in the list view,
but not in the web view in the TYPO3 backend.
This problem happens at least when migrating from TYPO3 v7 to v8 while
upgrading to flux 9.5.0.
Old content records exhibit this problem, while newly created content
is fine - TYPO3 takes care of modifying the "sorting" values correctly.
This wizard fixes the problematic sorting values by finding the largest
child sorting value and adjusting the parent's "sorting" accordingly,
as well as all following content element siblings.
Resolves: https://github.com/FluidTYPO3/flux/issues/1824
=> [FEATURE] Upgrade wizard for problematic content element "sorting" values

Classes/ViewHelpers/Grid/ColumnViewHelper.php
Viewhelper annotation was not up-to-date with current implementation of "allowedContentTypes" in  ColumnViewHelper
=> [DOC] update annotation for allowedContentTypes in ColumnViewHelper 

Classes/Updates/MigrateColPosWizard.php, ext_localconf.php
The v8 API is not available on TYPO3v10 and v11, so to support them
we have to use the new upgrade wizard API.
We drop support for TYPO3v8 for that feature.
See
https://docs.typo3.org/c/typo3/cms-core/9.5/en-us/Changelog/9.4/Feature-86076-NewAPIForUpgradeWizards.html
Resolves: https://github.com/FluidTYPO3/flux/issues/1934
Related: https://github.com/FluidTYPO3/flux/pull/1929
=> [BUGFIX] Use TYPO3v9 API for colPos upgrade wizard

Classes/Integration/HookSubscribers/DataHandlerSubscriber.php
Deleting content elements that are restricted in some way
(hidden, starttime, endtime, fe_group) is broken since commit
> [BUGFIX] Prevent error when moving/pasting content with deleted child
That commit was meant to fix a problem with deleted content elements.
This commit here actually only filters deleted elements instead of all.
Resolves: https://github.com/FluidTYPO3/flux/issues/1939
=> [BUGFIX] Allow deleting hidden content elements

Classes/Utility/ExtensionConfigurationUtility.php
When using ext:flux with PHP 8+, always the default extension configuration is returned. Also, the `['flux']['setup']`
extension configuration array key is not available when extension settings are processed in $GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['flux']
Refs #1977
=> [BUGFIX] Ensure correct extension configuration is returned in PHP8+

Classes/Controller/AbstractFluxController.php
Fix deprecation messages by checking for null values before passing p…arameter as non-nullable internal function parameters which is deprecated in >= PHP8.1.
Fixes issue #1964
=> #1964 Fix deprecation messages in PHP8.1

Classes/Provider/PageProvider.php, Classes/ViewHelpers/Content/GetViewHelper.php, Tests/Unit/Provider/SubPageProviderTest.php
Massive php warning spam,  suppressed by simple sanity checks.
=> [BUGFIX] Add several sanity checks to avoid php warnings

Classes/Backend/BackendLayoutDataProvider.php
only the uid of the page is read. But here all fields must be read, because later in PageProvider->getControllerActionReferenceFromRecord is checked whether the main template of the page is set. And this is then never set! Then the layout from the settings of the parent page is used by mistake.
=> [BUGFIX] Load entire record in BackendLayoutDataProvider->getBackendlayout

Classes/ViewHelpers/Field/Inline/FalViewHelper.php
in phpdoc it is written that how to render image with f:image but it will not crop the image if image.id will be supplied to src attribute. with image.uid it will crop the image. updated the phpdoc
=> [DOC] Correct flux:field.inline.fal image.uid usage in f:image

Classes/Form/Field/Text.php
This fix the bug which leads to an BE error for newly placed content elements with a flud:field.text and enabled rte. New placed content elements which are not saved doesn't have a pid in the record.
Related to issue [2078](https://github.com/FluidTYPO3/flux/issues/2078)
=> [BUGFIX] Tolerate record without pid

Classes/ViewHelpers/FormViewHelper.php
If $arguments['id'] is an integer an error gets thrown. This way the integer gets casted to a string and doesn't break the processing.
=> [BUGFIX] Cast "id" Form attribute to string

Classes/Builder/ContentTypeBuilder.php, Classes/Content/TypeDefinition/FluidFileBased/DropInContentTypeDefinition.php
Fixes a combined issue where template file paths would be wrong in BE context and the pi_flexform field would not be shown in record editing, for templates placed in the plug-and-play / drop-in directory.
=> [BUGFIX] Fix handling of drop-in templates

Classes/Integration/Configuration/SpooledConfigurationApplicator.php
We can ignore a missing database connection at this point. We cant do anything about a missing database connection. This Scenario is possible during first install.
In a Scenario, where flux is installed before first install, this happens:
1. Upon the last setup step, when finishing by sending the admin user credentials and some metadata, the BootCompletedEvent is fired which brings up the FluidTYPO3\Flux\Integration\Event\BootCompletedEventListener.
2. The `SpooledConfigurationApplicator` then in its `processData` calls `$this->spoolQueuedContentTypeRegistrations` in Line 71.
3. Then `$this->contentTypeBuilder->registerContentType` in Line 181 **requires a Database Connection** for registering the content types.
4. Because the **Database is not fully setup** yet, DBAL returns a …
=> [BUGFIX] Handle possible DBALException

Classes/Enum/ExtensionOption.php, Classes/Enum/FormOption.php, Classes/Integration/NormalizedData/DataAccessTrait.php, Classes/Provider/PageProvider.php, Classes/Utility/ExtensionConfigurationUtility.php, Classes/ViewHelpers/Form/Option/InheritanceModeViewHelper.php, Resources/Private/Language/locallang.xlf, Tests/Unit/Provider/PageProviderTest.php, Tests/Unit/ViewHelpers/Form/Option/InheritanceModeViewHelperTest.php, ext_conf_template.txt
Adds an extension configuration option and corresponding Form option and option ViewHelper which allows a site to control how Flux handles inheritance of FlexForm values (specific to pages).
Normally, Flux will only allow FlexForm values to be inherited from a parent page to children if the child uses the same page layout (template) as the parent page(s). This new option allows changing this inheritance mode from the default "restricted" to an "unrestricted" mode which allows FlexForm values to be inherited even if the child and parent uses different page layouts.
This is useful when you have different page templates which use the same FlexForm fields (for example, a shared set of fields) and you wish to inherit such fields from parents even if you use different page layouts on the …
=> [FEATURE] Add inheritance mode control

Classes/Form/Transformation/Transformer/FileTransformer.php, Tests/Mock/ExpressionBuilder.php, Tests/Mock/QueryBuilder.php, Tests/Mock/Result.php, Tests/Unit/Form/Transformation/Transformer/FileTransformerTest.php
FileRepository is broken in BE context for FlexForm-based relations.
Refs: #2139
Refs: https://forge.typo3.org/issues/104331
=> [BUGFIX] Avoid FileRepository for reading FAL relations

Classes/Form/AbstractFormField.php, Classes/Form/FieldInterface.php, Classes/Integration/FormEngine/ProtectValueWizard.php, Classes/Provider/AbstractProvider.php, Classes/Provider/PageProvider.php, Classes/ViewHelpers/Field/AbstractFieldViewHelper.php, Classes/ViewHelpers/FieldViewHelper.php, Resources/Private/Language/locallang.xlf, Tests/Unit/Integration/FormEngine/ProtectValueWizardTest.php, ext_localconf.php
Use `protect="1"` on fields to render a wizard check box which when toggled on, protects the current value of the field from being changed when the value changes in a parent record.
=> [FEATURE] Add ability to protect values from changing when inherited

Classes/Enum/ExtensionOption.php, Classes/Form/AbstractFormComponent.php, Classes/Form/Transformation/FormDataTransformer.php, Classes/Form/Transformation/Transformer/FileTransformer.php, Classes/Provider/AbstractProvider.php, Classes/Utility/ExtensionConfigurationUtility.php, Resources/Private/Language/locallang.xlf, Tests/Unit/Form/Transformation/Transformer/FileTransformerTest.php, ext_conf_template.txt
TYPO3 has a limitation (one among many) when dealing with with FAL references within FlexForms. The field name saved to sys_file_reference is unique to the DS but not unique to the parent field name context.
Usually we would solve this by extending foreign_match_fields but someone in their infinite wisdom decided that as part of the automatic TCA migration wizard that rewrites type=inline with FAL to type=file, the foreign_match_fields setting should be destroyed and type=file should not have any support whatsoever for this kind of advanced relation criteria.
We are therefore left with only one option: changing the field name of the FAL field to include the parent field name as prefix. This new extension feature enables that behavior.
Unfortunately this means that file references are …
=> [FEATURE] Add extension config to produce unique file field names

Classes/ViewHelpers/Field/AbstractMultiValueFieldViewHelper.php
Because of the error message:
Uncaught TYPO3 Exception FluidTYPO3\Flux\Form\AbstractMultiValueFormField::setMinItems(): Argument #1 ($minItems) must be of type int, string given, called in /var/www/html/vendor/fluidtypo3/flux/Classes/ViewHelpers/Field/AbstractMultiValueFieldViewHelper.php on line 91 thrown in file /var/www/html/vendor/fluidtypo3/flux/Classes/Form/AbstractMultiValueFormField.php in line 118
=> bugfix: type cast (int) in AbstractMultiValueFieldViewHelper.php

Classes/Builder/FlexFormBuilder.php
When you add a new page from list view via page (select position) then BeforeFlexFormDataStructureIdentifierInitializedEvent gives us the negative value of the page uid of the sibling to the choosen position. We need the real parent id though (as the documentation implies is always given).
=> [BUGFIX] make sure to have correct pid

Classes/Builder/RenderingContextBuilder.php
When using flux 10.0.10 on TYPO3v11, the deprecation log is full of
> Setting request from controllerContext in class
> TYPO3\CMS\Fluid\Core\Rendering\RenderingContext is deprecated.
> Use setRequest() directly.
> in typo3/sysext/fluid/Classes/Core/Rendering/RenderingContext.php line 205
The deprecation notice is only triggered when the context has no request yet.
To get rid of this notice, we simply set the request before setting the controller context.
=> [BUGFIX] Prevent TYPO3v11 controllerContext deprecation notice

Classes/Integration/HookSubscribers/DataHandlerSubscriber.php
When copying a page in TYPO3 v11.5.41, PHP 8.3.15 and flux 10.1.0 an exception occurs:
> (1/1) TypeError
> Cannot access offset of type string on string
> in typo3/sysext/core/Classes/Database/Query/QueryBuilder.php line 1368
Thanks to the following blog post for the solution: https://blog.wappler.systems/typo3-error-cannot-access-offset-of-type-string-on-string-at-querybuilder-update-command/
Resolves: https://github.com/FluidTYPO3/flux/issues/2196
=> [BUGFIX] Fix error when copying a page

.github/workflows/build.yml, composer.json
Require it only while running CI job to avoid any dependency concerns.
=> [TASK] Remove Coveralls as direct dependency

Classes/Provider/ProviderResolver.php, Tests/Unit/Provider/ProviderResolverTest.php
To my knowledge, this feature has never been used except in my own proof-of-concept environments. Given that it would need a rather excessive workaround to function on v13 it's probably best to simply remove the feature.
=> [REMOVAL] Remove feature to register Providers with TypoScript

Classes/Builder/ViewBuilder.php, Classes/Provider/AbstractProvider.php, Classes/Provider/PageProvider.php, Tests/Unit/Provider/PageProviderTest.php, Tests/Unit/Provider/ProviderTest.php
Adds a fallback handling which delivers template path setup based on Flux and provider extensions' paths when TypoScript can not be resolved. If TypoScript can be resolved, the path setup is read from plugin.tx_yourext (where "yourext" is your provider extension key) as usual.
=> [FEATURE] Deliver fallback TemplatePaths if unable to read TypoScript

Resources/Private/Language/de.locallang.xlf
Related: #1960
In TYPO3v12 it was not enough to just have the `de.locallang.xlf` file. I had to manually copy it into `var/labels/de/flux/Resources/Private/Language/`. Maybe this happens automatically when installing the extension.
=> [FEATURE] Add German translation

Classes/Form/AbstractInlineFormField.php
.. in TYPO3v12+ because that property has been removed.
Deprecation notice:
> FlexFormTools did an on-the-fly migration of a flex form data
> structure.
> This is deprecated and will be removed.
> Merge the following changes into the flex form definition
> "content.fieldname":
> The TCA field 'dummyField' of table 'dummyTable' is defined as type
> 'inline' with the 'appearance.showRemovedLocalizationRecords' option
> set. As this option is not evaluated anymore and no replacement
> exists, it should be removed from TCA.
TYPO3 core patch:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/69665
=> [BUGFIX] Remove TCA inline "showRemovedLocalizationRecords" property

Classes/Utility/ContentObjectFetcher.php, Tests/Unit/Integration/NormalizedData/DataAccessTraitTest.php
The ContentObjectFetcher was introduced in #2190 to have a common API for fetching the current content object across different TYPO3 versions.
This class logs a deprecation notice in TYPO3v12:
> ConfigurationManager->getContentObject() is deprecated since TYPO3 v12.4
> and will be removed in v13.0.
> Fetch the current content object from request attribute
> "currentContentObject" instead in
> vendor/typo3/cms-extbase/Classes/Configuration/ConfigurationManager.php
> line 96
To prevent this from happening, we check for the TYPO3 version and always use the request instead of the configuration manager in TYPO3v12+.
Note: In TYPO3v12, "$request->getAttribute('currentContentObject')" does not always return the content object.
We thus fall back to …
=> [BUGFIX] Always fetch ContentObject from request in TYPO3v12+

Classes/Form/AbstractMultiValueFormField.php, Tests/Unit/Content/TypeDefinition/RecordBased/RecordBasedContentGridProviderTest.php, Tests/Unit/Form/Container/SectionTest.php, Tests/Unit/Form/Field/SelectTest.php
TYPO3v12 introduced associative array keys for items in TCA select fields: label, value, icon, group.
The indexed item arrays were deprecated at the same time, throwing warnings in TYPO3v12+:
> FlexFormTools did an on-the-fly migration of a flex form data structure.
> This is deprecated and will be removed.
> Merge the following changes into the flex form definition "content.field":
> The TCA field 'dummyField' of table 'dummyTable' uses the legacy way of
> defining 'items'.
> Please switch to associated array keys:
> label, value, icon, group, description.
> in vendor/typo3/cms-core/Classes/Configuration/FlexForm/FlexFormTools.php
> line 1127
Changelog:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.3/Feature-99739-AssociativeArrayKeysForTCAIte …
=> [BUGFIX] Use associative array for TCA items

Classes/Integration/HookSubscribers/DataHandlerSubscriber.php
TYPO3v12 brings a deprecation warning when copying a container with nested content elements:
> ExpressionBuilder::andX() will be removed in TYPO3 v13.0.
> Use ExpressionBuilder::and() instead. in
> vendor/typo3/cms-core/Classes/Database/Query/Expression/ExpressionBuilder.php
> line 72
The `and` method was introduced in TYPO3v11, and in v12 it was deprecated.
This patch switches the order: When `and` is available, it is used, and the code falls back to `andX` for TYPO3v10.
Changelog:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-97354-ExpressionBuilderMethodsAndXAndOrX.html
Resolves: https://github.com/FluidTYPO3/flux/issues/2233
Related: f3826ca0d5509d17b16b4a0209507ec144524c0c.
=> [BUGFIX] Use ExpressionBuilder::and when available, andX as fallback
